name: "[BUILD - PR DEVELOPER]"

on:
  push:
    branches:
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build:prod
  pull-request:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: cheking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: NOME BRANCHH
        run: echo ${{ github.head_ref }}

      - name: Create Pull Request - ${{ github.ref_name }} into release
        uses: peter-evans/create-pull-request@v3
        with:
          branch: feature/melhorias-pipeline
          base: developer
          title: PR ${{ github.ref_name }} into release
          commiter: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body: Pull Request - ${{ github.ref_name }} into release
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false
