name: "[BUILDD]"

on:
  push:
    branches:
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Teste
        run: echo PASSOU BUILD
        
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Open PR
        id: open_pr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: feature/melhorias-pipeline
          to-branch: developer
          repository-owner: ${{ env.GIT_COMMIT_AUTHOR_NAME }}
          repository: app-blog-pessoal
          
      - name: Echo mergeable PR number
        run: echo ${{ steps.open_pr.outputs.pull_number }}
    