name: "[BUILDD]"

on:
  push:
    branches:
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Teste
        run: echo PASSOU BUILD
        
  jekyll_build:
    runs-on: ubuntu-latest

    steps:      
      - name: Initialize Pull Request
        uses: gha-utilities/init-pull-request@v0.3.3
        with:
          verbose: true
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          head: developer
          base: feature/melhorias-pipeline
          title: 'Updates site files from latest Actions build'
          body: >
            Perhaps a multi-line description
            about latest features and such.