name: "[BUILD - PR DEVELOPER]"

on:
  push:
    branches:
      - "feature/**"

jobs:
  prepare-enviroment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo Rodando Build      
