name: "[BUILDD]"

on:
  push:
    branches:
      - "feature/**"

jobs:          
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: cheking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
      
      - name: Create Pull Request - release into master
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: developer #into
          base: feature/melhorias-pipeline #from
          title: PR feature/melhorias-pipeline into developer
          commiter: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            Pull Request - feature/melhorias-pipeline into developer
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false
      
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1


        