name: "[BUILD]"

on:
  push:
    branches:
      - "feature/**"

jobs:          
  create-auto-pull-request:    
    needs: test
    runs-on: ubuntu-latest    
    steps:      
      - name: Open PR Develop
        id: open_pr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: ${{ github.ref_name }}
          to-branch: develop
          repository-owner: ${{ github.repository_owner }}
          repository: ${{ github.event.repository.name }}
        