name: '2 - Create PR Release'

on:
  pull_request:
    types:
      - closed
    branches:
      - developer  

jobs:
  create-auto-pull-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest    
    steps:      
      - name: Open PR Release
        id: open_pr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: ${{ github.ref_name }}
          to-branch: release
          repository-owner: ${{ github.repository_owner }}
          repository: ${{ github.event.repository.name }}