name: '[PR RELEASE]'

on:
  pull_request:
    types:
      - closed
    branches:
      - developer  

jobs:  
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: cheking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
      
      - name: Create Pull Request - developer into release
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release #into
          base: developer #from
          title: PR developer into release
          commiter: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            Pull Request - developer into release
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false