name: '[PR RELEASE]'

on:
  pull_request:
    types:
      - closed
    branches:
      - developer  

jobs:  
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Update AUTHORS
        run: |
          git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update authors
          title: PR developer into releae
          body: Pull Request - developer into release
          branch: developer #from
          base: release #into
      - name: Result Pull Request
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"