name: '[PR RELEASE]'

on:
  pull_request:
    types:
      - closed
    branches:
      - developer  

jobs:  
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update AUTHORS
        run: |
          git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update authors
          title: PR developer into releae
          body: Pull Request - developer into release
          branch: developer #from
          base: release #into