name: '3 - Create PR Master'

on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:  
  create-auto-pull-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest    
    steps:      
      - name: Open PR Master
        id: open_pr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: ${{ github.ref_name }}
          to-branch: master
          repository-owner: ${{ github.repository_owner }}
          repository: ${{ github.event.repository.name }}