name: '[PR MASTER]'

on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:  
  pullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: cheking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
      
      - name: Create Pull Request - ${{ github.ref_name }} into master
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release
          base: master
          title: PR ${{ github.ref_name }} into master
          commiter: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            Pull Request - ${{ github.ref_name }} into master
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false