name: '[DEPLOY PRODUCTION]'

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: update author information
        run: echo "TESTE"